# Punctuation and capitalization with pretrained BERT models

trainer:
  gpus: 1 # the number of gpus, 0 for CPU
  num_nodes: 1
  max_epochs: 3
  max_steps: null # precedence over max_epochs
  accumulate_grad_batches: 1 # accumulates grads every k batches
  amp_level: O0 # O1/O2 for mixed precision
  distributed_backend: ddp
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  row_log_interval: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations

model:
  data_dir: ??? # /path/to/data
  max_seq_length: 128
  pad_label: 'O'
  ignore_extra_tokens: false
  ignore_start_end: false
  use_cache: true

  train_ds:
    prefix: train
    shuffle: true
    num_samples: -1
    batch_size: 32
    num_workers:  2
    pin_memory: false
    drop_last: false

  validation_ds:
    prefix: dev
    shuffle: false
    num_samples: -1
    batch_size: 32
    num_workers:  2
    pin_memory: false
    drop_last: false

  language_model:
    pretrained_model_name: bert-base-uncased
    bert_checkpoint: null
    bert_config: null
    tokenizer: nemobert # only used if using custom checkpoint
    vocab_file: null
    tokenizer_model: null # only used if tokenizer is sentencepiece
    do_lower_case: true # true for uncased models, false for cased models

  punct_head:
    punct_num_fc_layers: 1
    fc_dropout: 0.1
    activation: 'relu'
    log_softmax: True
    use_transformer_init: True

  capit_head:
    capit_num_fc_layers: 1
    fc_dropout: 0.1
    activation: 'relu'
    log_softmax: True
    use_transformer_init: True

  optim:
    name: adam
    lr: 2e-5
    args:
      name: auto
      params:
        weight_decay: 0.01

    sched:
      name: WarmupAnnealing
      iters_per_batch: null # computed at runtime
      max_steps: null # computed at runtime or explicitly set here

      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

      # scheduler config override
      args:
        name: auto
        params:
          warmup_steps: null
          warmup_ratio: 0.1
          last_epoch: -1

exp_manager:
  root_dir: null  # root_dir for your experiment, if None, defaults to "./NeMo_experiments"
  name: Punctuation_and_Capitalization  # The name of your model
  create_tensorboard_logger: True  # Whether you want exp_manger to create a tb logger
  create_checkpoint_callback: True  # Whether you want exp_manager to create a modelcheckpoint callback

hydra:
  run:
    dir: .
  job_logging:
    root:
      handlers: null
