model = "Jasper"
sample_rate = 16000

[AudioToTextDataLayer]
int_values = false
min_duration = 0.0
max_duration = 16.7
trim_silence = true
load_audio = true
drop_last = false
normalize_transcripts = true

    [AudioToTextDataLayer.train]
    shuffle = true

    [AudioToTextDataLayer.eval]
    shuffle = false
    max_duration = +inf

[AudioPreprocessing]
window_size = 0.02
window_stride = 0.01
window = "hann"
normalize = "per_feature"
preemph = 0.97
n_fft = 512
features = 64
lowfreq = 0
feat_type = "logfbank"
dither = 0.00001
pad_to = 16
frame_splicing = 1
stft_conv = true

[MultiplyBatch]

[SpectrogramAugmentation]

[JasperEncoder]
activation = "relu"
conv_mask = true

    [[JasperEncoder.jasper]]
    filters = 256
    repeat = 1
    kernel = [11]
    stride = [2]
    dilation = [1]
    dropout = 0.2
    residual = false

    [[JasperEncoder.jasper]]
    filters = 256
    repeat = 4
    kernel = [11]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 256
    repeat = 4
    kernel = [11]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 384
    repeat = 4
    kernel = [13]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 384
    repeat = 4
    kernel = [13]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 512
    repeat = 4
    kernel = [17]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 512
    repeat = 4
    kernel = [17]
    stride = [1]
    dilation = [1]
    dropout = 0.2
    residual = true

    [[JasperEncoder.jasper]]
    filters = 640
    repeat = 4
    kernel = [21]
    stride = [1]
    dilation = [1]
    dropout = 0.3
    residual = true

    [[JasperEncoder.jasper]]
    filters = 640
    repeat = 4
    kernel = [21]
    stride = [1]
    dilation = [1]
    dropout = 0.3
    residual = true

    [[JasperEncoder.jasper]]
    filters = 768
    repeat = 4
    kernel = [25]
    stride = [1]
    dilation = [1]
    dropout = 0.3
    residual = true

    [[JasperEncoder.jasper]]
    filters = 768
    repeat = 4
    kernel = [25]
    stride = [1]
    dilation = [1]
    dropout = 0.3
    residual = true

    [[JasperEncoder.jasper]]
    filters = 896
    repeat = 1
    kernel = [29]
    stride = [1]
    dilation = [2]
    dropout = 0.4
    residual = false

    [[JasperEncoder.jasper]]
    filters = 1024
    repeat = 1
    kernel = [1]
    stride = [1]
    dilation = [1]
    dropout = 0.4
    residual = false

[labels]
labels = [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]
