name: "DeepGriffinLim"
sample_rate: 22050
n_fft: 1024
hop_length: 256
destination: "/tmp"

model:
  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.NoisySpecsDataset"
      destination: ${destination}
      subdir: "/train"
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      num_snr: 1
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 16
      num_workers: 1

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.NoisySpecsDataset"
      destination: ${destination}
      subdir: "/valid"
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      num_snr: 1

    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 16
      num_workers: 1

  preprocessor:
    valid_filelist: none
    train_filelist: none
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    num_snr: 1
    destination: ${destination}

  degli:
    _target_: nemo.collections.tts.modules.degli.DegliModule
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    depth: 1
    out_all_block: True
    tiny: False # overrides all below configurations if true.
    layers: 6
    k_x: 3
    k_y: 3
    s_x: 1
    s_y: 2
    widening: 16
    use_bn: False
    linear_finalizer: True
    convGlu: False
    act: relu
    act2: selu
    glu_bn: True
    use_weight_norm: True


  optim:
    name: novograd
    lr: 0.01
    weight_decay: 0.001

    sched:
      name: ReduceLROnPlateau
      mode: min
      factor: 0.6
      patience: 5
      verbose: True
      threshold: 0.01
      threshold_mode: 'rel'
      cooldown: 0
      min_lr: 0.00001
      eps: 1.e-08

  train_params:
    repeat_training: 2
    repeat_validation: 32
    sampling_rate: ${sample_rate}

trainer:
  gpus: 1 # number of gpus
  max_epochs: 200
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 2000
  log_every_n_steps: 200
  check_val_every_n_epoch: 5
  precision: 32
  gradient_clip_val: 4.0

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
