name: "EncoderDecoderMelToSpec"
sample_rate: 22050
n_fft: 1024
hop_length: 256
destination: "/tmp"

model:
  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.NoisySpecsDataset"
      destination: ${destination}
      subdir: "/train"
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      num_snr: 1
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 16
      num_workers: 1

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.NoisySpecsDataset"
      destination: ${destination}
      subdir: "/valid"
      n_fft: ${n_fft}
      hop_length: ${hop_length}
      num_snr: 1

    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 16
      num_workers: 1

  preprocessor:
    valid_filelist: none
    train_filelist: none
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    num_snr: 1
    destination: ${destination}

  mel2spec:
    _target_: nemo.collections.tts.modules.ed_mel2spec.EDMel2SpecModule
    n_fft: ${n_fft}
    hop_length: ${hop_length}
    mel_fmin: 0
    mel_fmax: null
    mel_freq: 80
    layers: 8
    sampling_rate: ${sample_rate}
    widening: 16
    use_batchnorm: True
    droprate: 0.2
    num_dropout: 3
    pre_final_lin: True
    act1: lrelu
    act2: relu
    use_weight_norm: False

  optim:
    name: adam
    lr: 5.e-4
    weight_decay: 1.e-3

    sched:
      name: ReduceLROnPlateau
      mode: min
      factor: 0.8
      patience: 5
      verbose: True
      threshold: 0.01
      threshold_mode: 'rel'
      cooldown: 0
      min_lr: 5.e-5
      eps: 1.e-08

  train_params:
    lreg_factor: 1.0
    loss_mode: 3
    validate_scores: True # Slow!

trainer:
  gpus: 1 # number of gpus
  max_epochs: 200
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 2000
  log_every_n_steps: 200
  check_val_every_n_epoch: 10
  precision: 32
  gradient_clip_val: 4.0

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
