name: "FastPitch"
sample_rate: 22050

train_dataset: ???
validation_datasets: ???
sup_data_path: ???
sup_data_types: [ "duration_prior", "pitch" ]

phoneme_dict_path: "scripts/tts_dataset_files/cmudict-0.7b"
heteronyms_path: "scripts/tts_dataset_files/heteronyms-030921"
whitelist_path: "nemo_text_processing/text_normalization/en/data/whitelist_lj_speech.tsv"

model:
  learn_alignment: true
  n_speakers: 1
  symbols_embedding_dim: 384
  max_token_duration: 75
  n_mel_channels: 80
  pitch_embedding_kernel_size: 3
  window: hann
  n_window_size: 1024
  n_window_stride: 256
  lowfreq: 0
  highfreq: 8000
  pitch_fmin: 80
  pitch_fmax: 640
  pitch_avg: 211.27540199742586
  pitch_std: 52.1851002822779

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.torch.data.TTSDataset"
      manifest_filepath: ${train_dataset}
      sample_rate: ${sample_rate}
      sup_data_path: ${sup_data_path}
      sup_data_types: ${sup_data_types}
      n_fft: ${model.n_window_size}
      win_length: ${model.n_window_size}
      hop_length: ${model.n_window_stride}
      window: ${model.window}
      n_mels: ${model.n_mel_channels}
      lowfreq: ${model.lowfreq}
      highfreq: ${model.highfreq}
      max_duration: null
      min_duration: 0.1
      ignore_file: null
      trim: False
      pitch_fmin: ${model.pitch_fmin}
      pitch_fmax: ${model.pitch_fmax}
      pitch_norm: true
      pitch_avg: ${model.pitch_avg}
      pitch_std: ${model.pitch_std}

      text_normalizer:
        _target_: "nemo_text_processing.text_normalization.normalize.Normalizer"
        lang: "en"
        input_case: "cased"
        whitelist: ${whitelist_path}

      text_normalizer_call_args:
        verbose: False
        punct_pre_process: True
        punct_post_process: True

      text_tokenizer:
        _target_: "nemo.collections.tts.torch.tts_tokenizers.EnglishPhonemesTokenizer"
        punct: True
        stresses: True
        chars: True
        space: ' '
        silence: null
        apostrophe: True
        sep: '|'
        add_blank_at: null
        pad_with_space: True
        g2p:
          _target_: "nemo.collections.tts.torch.g2ps.EnglishG2p"
          phoneme_dict: ${phoneme_dict_path}
          heteronyms: ${heteronyms_path}
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32
      num_workers: 12


  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.torch.data.TTSDataset"
      manifest_filepath: ${validation_datasets}
      sample_rate: ${sample_rate}
      sup_data_path: ${sup_data_path}
      sup_data_types: ${sup_data_types}
      n_fft: ${model.n_window_size}
      win_length: ${model.n_window_size}
      hop_length: ${model.n_window_stride}
      window: ${model.window}
      n_mels: ${model.n_mel_channels}
      lowfreq: ${model.lowfreq}
      highfreq: ${model.highfreq}
      max_duration: null
      min_duration: null
      ignore_file: null
      trim: False
      pitch_fmin: ${model.pitch_fmin}
      pitch_fmax: ${model.pitch_fmax}
      pitch_norm: true
      pitch_avg: ${model.pitch_avg}
      pitch_std: ${model.pitch_std}

      text_normalizer:
        _target_: "nemo_text_processing.text_normalization.normalize.Normalizer"
        lang: "en"
        input_case: "cased"
        whitelist: ${whitelist_path}

      text_normalizer_call_args:
        verbose: False
        punct_pre_process: True
        punct_post_process: True

      text_tokenizer:
        _target_: "nemo.collections.tts.torch.tts_tokenizers.EnglishPhonemesTokenizer"
        punct: True
        stresses: True
        chars: True
        space: ' '
        silence: null
        apostrophe: True
        sep: '|'
        add_blank_at: null
        pad_with_space: True
        g2p:
          _target_: "nemo.collections.tts.torch.g2ps.EnglishG2p"
          phoneme_dict: ${phoneme_dict_path}
          heteronyms: ${heteronyms_path}

    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32
      num_workers: 8

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    dither: 0.0
    features: ${model.n_mel_channels}
    frame_splicing: 1
    highfreq: ${model.highfreq}
    log: true
    log_zero_guard_type: add
    log_zero_guard_value: 1e-05
    lowfreq: ${model.lowfreq}
    mag_power: 1.0
    n_fft: ${model.n_window_size}
    n_window_size: ${model.n_window_size}
    n_window_stride:  ${model.n_window_stride}
    normalize: null
    pad_to: 1
    pad_value: 0
    preemph: null
    sample_rate: ${sample_rate}
    window: ${model.window}
    window_size: null
    window_stride: null

  input_fft: #n_embed and padding_idx are added by the model
    _target_: nemo.collections.tts.modules.transformer.FFTransformerEncoder
    n_layer: 6
    n_head: 1
    d_model: ${model.symbols_embedding_dim}
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0
    d_embed: ${model.symbols_embedding_dim}

  output_fft:
    _target_: nemo.collections.tts.modules.transformer.FFTransformerDecoder
    n_layer: 6
    n_head: 1
    d_model: ${model.symbols_embedding_dim}
    d_head: 64
    d_inner: 1536
    kernel_size: 3
    dropout: 0.1
    dropatt: 0.1
    dropemb: 0.0

  alignment_module:
    _target_: nemo.collections.tts.modules.aligner.AlignmentEncoder
    n_text_channels: ${model.symbols_embedding_dim}

  duration_predictor:
    _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
    input_size: ${model.symbols_embedding_dim}
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 2

  pitch_predictor:
    _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
    input_size: ${model.symbols_embedding_dim}
    kernel_size: 3
    filter_size: 256
    dropout: 0.1
    n_layers: 2

  optim:
    name: lamb
    lr: 1e-1
    betas: [0.9, 0.98]
    weight_decay: 1e-6

    sched:
      name: NoamAnnealing
      warmup_steps: 1000
      last_epoch: -1
      d_model: 1  # Disable scaling based on model dim

trainer:
  devices: -1 # number of gpus
  max_epochs: 1500
  num_nodes: 1
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  gradient_clip_val: 1000.0
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 100
  check_val_every_n_epoch: 5

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: v_loss
