name: FastSpeech2_HiFiGAN_E2E

# Dataset info
train_dataset: ???
validation_datasets: ???
mappings_file: ???  # JSON file with word->phone and phone->idx mappings
ignore_file: ???


model:
  lr: 0.5
  splice_length: 64  # Length in frames
  mel_loss_coeff: 45.
  pitch_loss_coeff: 0.003
  energy_loss_coeff: 0.03
  add_energy_predictor: True
  add_pitch_predictor: True
  mappings_filepath: ${mappings_file}
  sample_rate: 22050
  n_mels: 80
  hop_size: 256

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.FastSpeech2Dataset"
      manifest_filepath: ${train_dataset}
      mappings_filepath: ${mappings_file}
      sample_rate: ${model.sample_rate}
      max_duration: null
      min_duration: 0.75
      ignore_file: ${ignore_file}
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 64
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.FastSpeech2Dataset"
      manifest_filepath: ${validation_datasets}
      mappings_filepath: ${mappings_file}
      sample_rate: ${model.sample_rate}
      ignore_file: ${ignore_file}
      trim: false
      load_supplementary_values: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 64
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.features.FilterbankFeatures
    dither: 0.0
    nfilt: ${n_mels}
    frame_splicing: 1
    highfreq: 8000
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: ${model.hop_size}
    normalize: null
    pad_to: 0
    preemph: null
    sample_rate: ${model.sample_rate}
    window: hann

  # FFTransformer encoder
  encoder:
    _target_: nemo.collections.tts.modules.fastspeech2.FastSpeech2Encoder
    d_model: 256
    n_layers: 4
    n_attn_heads: 2
    d_attn_head: 256
    d_inner: 1024
    kernel_size: 9
    dropout: 0.1
    attn_dropout: 0.1
    n_embed: 74   # Should match number of tokens in symbol set +1 (pad_idx)
    padding_idx: 73

  # VarianceAdaptor
  variance_adaptor:
    _target_: nemo.collections.tts.modules.fastspeech2.VarianceAdaptor
    d_model: 256
    dropout: 0.2
    dur_d_hidden: 256
    dur_kernel_size: 3

    pitch: ${model.add_pitch_predictor}
    log_pitch: True
    n_f0_bins: 256
    pitch_kernel_size: 3
    pitch_min: 80.0
    pitch_max: 800.0
    energy: ${model.add_energy_predictor}
    n_energy_bins: 256
    energy_kernel_size: 3
    energy_min: 0.0
    energy_max: 600.0

  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    upsample_kernel_sizes: [16,16,4,4]
    upsample_rates: [8,8,2,2]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
    resblock: 1
    initial_input_size: 256
    apply_weight_init_conv_pre: true

trainer:
  gpus: 1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  log_every_n_steps: 200
  check_val_every_n_epoch: 25
  move_metrics_to_cpu: False
  precision: 16

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True