name: FastSpeech2
sample_rate: 22050
n_mels: 80

# Dataset info
train_dataset: ???
validation_datasets: ???
mappings_file: ???  # JSON file with word->phone and phone->idx mappings
ignore_file: ???

model:
  add_pitch_predictor: True
  add_energy_predictor: True
  d_model: 256
  duration_coeff: 0.25
  mappings_filepath: ${mappings_file}

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.FastSpeech2Dataset"
      manifest_filepath: ${train_dataset}
      mappings_filepath: ${mappings_file}
      sample_rate: ${sample_rate}
      max_duration: null
      min_duration: 0.1
      ignore_file: ${ignore_file}
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 64
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.FastSpeech2Dataset"
      manifest_filepath: ${validation_datasets}
      mappings_filepath: ${mappings_file}
      sample_rate: ${sample_rate}
      ignore_file: ${ignore_file}
      trim: false
      load_supplementary_values: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 64
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    dither: 0.0
    nfilt: ${n_mels}
    frame_splicing: 1
    highfreq: 8000
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: 1024
    n_window_size: 1024
    n_window_stride: 256
    normalize: null
    pad_to: 16
    pad_value: -11.52
    preemph: null
    sample_rate: ${sample_rate}
    window: hann

  # FFTransformer encoder
  encoder:
    _target_: nemo.collections.tts.modules.fastspeech2.FastSpeech2Encoder
    d_model: ${model.d_model}
    n_layers: 4
    n_attn_heads: 2
    d_attn_head: 256
    d_inner: 1024
    kernel_size: 9
    dropout: 0.1
    attn_dropout: 0.1
    n_embed: 74   # Should match number of tokens in symbol set +1 (pad_idx)
    padding_idx: 73

  # FFTransformer mel spec decoder
  decoder:
    _target_: nemo.collections.tts.modules.fastspeech2.MelSpecDecoder
    d_model: ${model.d_model}
    d_out: ${n_mels}
    n_layers: 4
    n_attn_heads: 2
    d_attn_head: 256
    d_inner: 1024
    kernel_size: 9
    dropout: 0.1
    attn_dropout: 0.1

  # VarianceAdaptor
  variance_adaptor:
    _target_: nemo.collections.tts.modules.fastspeech2.VarianceAdaptor
    d_model: ${model.d_model}
    dropout: 0.2
    dur_d_hidden: 256
    dur_kernel_size: 3
    pitch: ${model.add_pitch_predictor}
    log_pitch: True
    n_f0_bins: 256
    pitch_kernel_size: 3
    pitch_min: 80.0
    pitch_max: 800.0
    energy: ${model.add_energy_predictor}
    n_energy_bins: 256
    energy_kernel_size: 3
    energy_min: 0.0
    energy_max: 600.0

  optim:
    name: adam
    betas: [0.9,0.98]
    lr: 1e-3
    weight_decay: 1e-6
    # scheduler setup
    sched:
      name: NoamAnnealing
      warmup_steps: 4000
      min_lr: 1e-5
      d_model: ${model.d_model}

trainer:
  gpus: 1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 200
  check_val_every_n_epoch: 25

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: True
  create_checkpoint_callback: True
