name: &name "UniGlow"
sample_rate: &sr 22050
n_fft: &n_fft 1024
n_mels: &n_mels 80
fmax: &fmax 8000
pad_value: &pad_value -11.52
train_dataset: ???
validation_datasets: ???
resume_from_ckpt: null

model:
  sigma: 1.0
  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${train_dataset}
      max_duration: null
      min_duration: 0.1
      n_segments: 16384
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 12
      num_workers: 4

  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.datalayers.AudioDataset"
      manifest_filepath: ${validation_datasets}
      max_duration: null
      min_duration: 0.1
      n_segments: 49152   # 3 secs
      trim: false
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 12
      num_workers: 4

  preprocessor:
    _target_: nemo.collections.asr.parts.features.FilterbankFeatures
    dither: 0.0
    nfilt: *n_mels
    frame_splicing: 1
    highfreq: *fmax
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    lowfreq: 0
    mag_power: 1.0
    n_fft: *n_fft

    # UniGlow is currently hardcoded to these values for window size and stride
    # Changing these parameters are not recommended
    n_window_size: 1024
    n_window_stride: 256

    normalize: null
    pad_to: 0 #16
    pad_value: *pad_value
    preemph: null
    sample_rate: *sr
    stft_conv: true
    window: hann

  uniglow:
    n_flows: 16
    n_group: 8
    n_mel_channels: *n_mels
    n_wn_channels: 256
    n_wn_layers: 8
    wn_kernel_size: 3
    stft_loss_coef: 0.1

  optim:
    name: adam
    lr: 1e-4

trainer:
  gpus: 1 # number of gpus
  max_epochs: ???
  num_nodes: 1
  accelerator: ddp
  accumulate_grad_batches: 1
  checkpoint_callback: False  # Provided by exp_manager
  logger: False  # Provided by exp_manager
  flush_logs_every_n_steps: 1000
  log_every_n_steps: 200
  check_val_every_n_epoch: 25
  precision: 16

exp_manager:
  exp_dir: null
  name: *name
  create_tensorboard_logger: True
  create_checkpoint_callback: True
