name: megatron_ptune_t5

trainer:
  devices: 2
  accelerator: gpu
  num_nodes: 1
  precision: 16
  logger: False # logger provided by exp_manager
  checkpoint_callback: False
  replace_sampler_ddp: False
  max_epochs: 3
  max_steps: null # consumed_samples = global_step * micro_batch_size * data_parallel_size * accumulate_grad_batches
  log_every_n_steps: 10
  val_check_interval: 300
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0

exp_manager:
  explicit_log_dir: null
  exp_dir: null
  name: megatron_ptune_t5
  create_wandb_logger: False
  wandb_logger_kwargs:
    project: null
    name: null
  resume_if_exists: True
  resume_ignore_no_checkpoint: True
  create_checkpoint_callback: True
  checkpoint_callback_params:
    monitor: val_acc
    save_top_k: 10
    mode: max
    always_save_nemo: False # TODO: add support
    filename: 'megatron_t5--{val_acc:.3f}-{step}'
    model_parallel_size: ${model.tensor_model_parallel_size}
    save_best_model: True

model:
  tensor_model_parallel_size: 1
  seed: 1234
  nemo_path: ptune_t5_model.nemo # filename to save the model and associated artifacts to .nemo file
  use_lm_finetune: False # whether fine tune the language model
  pseudo_token: '[PROMPT]' # pseudo prompt tokens
  decoder_seq_length: 10 # number to tokens for decoder to generate

  language_model:
    nemo_file: null

  prompt_encoder:
    template: [3, 3, 0]
    dropout: 0.0
    num_layers: 2
    task_dependent: true # whether the prompt encoder conditions on the task name or not, useful for multiple tasks

  task_processors:
    - taskname: qa-task
      template: "{v0} Context: {context}{v1} Question: {question}?{v2} Answer:"
      limit_length_field: 'context' 
    - taskname: sentiment-task  
      template: "{v0}{v1} Sentence: {sentence}{v2} Sentiment:"
      limit_length_field: 'sentence' 

  data:
    train_ds:
      file_path: ???
      batch_size: 32
      shuffle: True
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

    validation_ds:
      file_path: ???
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

    test_ds:
      file_path: ???
      batch_size: 32
      shuffle: False
      num_workers: 8
      pin_memory: True
      max_seq_length: 512

  optim:
    name: fused_adam
    lr: 1e-5
    weight_decay: 0.0
    # scheduler setup
    sched:
      name: WarmupAnnealing
      # Scheduler params
      warmup_steps: null
      warmup_ratio: 0.1
      last_epoch: -1
      # pytorch lightning args
      monitor: val_loss
      reduce_on_plateau: false

  # List of some sample queries for inference after training is done
  infer_samples:
    - {"sentence": "The NTSB said investigators are set to conduct sight distance tests on July 18 , using trains similar to those involved in the accident .", "prompt_tag": "sentiment-task"}
    - {"sentence": "New Delhi , July 17 -- Sahlberg Teppo , Kallio Timo and Mustonen Tuomas of M Real OYJ , Espoo , Finland have developed novel markings and methods of producing the same .", "prompt_tag": "sentiment-task"}
    - {"sentence": "Operating profit excluding non-recurring items was EUR 7.8 million compared to EUR 11.2 million .", "prompt_tag": "sentiment-task"}
    - {"sentence": "Glaston 's own glass processing unit , Tamglass Glass Processing , is a manufacturer of high quality safety glass products , and operates in Finland .", "prompt_tag": "sentiment-task"}
    - {"sentence": "CHS Expo Freight is a major Finnish fair , exhibition and culture logistics company that provides logistics services to various events by land , air and sea .", "prompt_tag": "sentiment-task"}
    - {"sentence": "For example , net sales increased by 5.9 % from the first quarter , and EBITDA increased from a negative EUR 0.2 mn in the first quarter of 2009 .", "prompt_tag": "sentiment-task"}
